// @ts-check

import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { themes as prismThemes } from 'prism-react-renderer';

const root = path.dirname(fileURLToPath(import.meta.url));

/**
 * The manifest is the single source of truth for what the site contains, so the
 * configuration derives from it rather than repeating it.
 */
const sources = JSON.parse(readFileSync(path.join(root, 'sources.json'), 'utf8'));

const currentVersion = sources.versions.find((version) => version.current);
const olderVersions = sources.versions.filter((version) => !version.current);

if (!existsSync(path.join(root, 'content'))) {
    throw new Error(
        'The content directory does not exist. The documentation is pulled from the package ' +
            'repositories rather than committed here, so run `npm run pull` before building.',
    );
}

/**
 * Sends "Edit this page" to the repository that owns the page. A page under
 * `content/schema` is Schema's page; editing it here would edit a copy that the
 * next pull throws away.
 */
function editUrl({ version, docPath }) {
    const [name, ...rest] = docPath.split('/');
    const pkg = sources.packages[name];
    const pin = (sources.versions.find((candidate) => (candidate.current ? 'current' : candidate.name) === version)
        ?? currentVersion).packages[name];

    if (!pkg || !pin || rest.length === 0) {
        return undefined;
    }

    return `${pkg.repo.replace(/\.git$/, '')}/edit/${pin.ref}/docs/${rest.join('/')}`;
}

/** @type {import('@docusaurus/types').Config} */
const config = {
    title: 'Dirthara',
    tagline: 'Small, sharp PHP packages for talking to a database.',
    favicon: 'img/favicon.png',

    url: 'https://dirthara.github.io',
    baseUrl: '/docs/',
    organizationName: 'dirthara',
    projectName: 'docs',
    trailingSlash: false,

    // A broken link is a 404 that nobody notices until a reader hits it. The
    // markdown comes from the package repositories, so a build failure here is
    // how a bad relative link in a package gets found at all.
    onBrokenLinks: 'throw',
    onBrokenAnchors: 'throw',

    markdown: {
        hooks: {
            onBrokenMarkdownLinks: 'throw',
            onBrokenMarkdownImages: 'throw',
        },
    },

    future: {
        // Opts in to the behaviour Docusaurus v4 will make default, so the
        // upgrade is not a migration. This also selects the rspack bundler,
        // which is why @docusaurus/faster is a dependency: it builds this site
        // in a quarter of the time webpack takes.
        v4: true,
    },

    i18n: {
        defaultLocale: 'en',
        locales: ['en'],
    },

    presets: [
        [
            'classic',
            /** @type {import('@docusaurus/preset-classic').Options} */
            ({
                docs: {
                    // Generated by scripts/pull-docs.mjs, not committed. Named
                    // `content` rather than `docs` because a `docs/docs` inside
                    // a repository called `docs` reads like a mistake.
                    path: 'content',
                    routeBasePath: '/',
                    sidebarPath: './sidebars.mjs',
                    editUrl,
                    showLastUpdateTime: true,
                    versions: {
                        current: {
                            label: currentVersion.label ?? currentVersion.name,
                            path: currentVersion.name,
                            banner: currentVersion.banner ?? 'none',
                        },
                        ...Object.fromEntries(
                            olderVersions.map((version) => [
                                version.name,
                                {
                                    label: version.label ?? version.name,
                                    path: version.name,
                                    banner: version.banner ?? 'none',
                                },
                            ]),
                        ),
                    },
                },
                blog: {
                    path: 'blog',
                    routeBasePath: 'blog',
                    blogTitle: 'Dirthara release notes',
                    blogDescription: 'Releases and announcements for the Dirthara packages.',
                    showReadingTime: true,
                    onInlineTags: 'throw',
                    onInlineAuthors: 'throw',
                    onUntruncatedBlogPosts: 'throw',
                    feedOptions: {
                        type: 'all',
                        title: 'Dirthara',
                        description: 'Releases and announcements for the Dirthara packages.',
                        copyright: `Copyright © ${new Date().getFullYear()} Dirthara`,
                    },
                },
                theme: {
                    customCss: './src/css/custom.css',
                },
                sitemap: {
                    changefreq: 'weekly',
                },
            }),
        ],
    ],

    themeConfig:
        /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
        ({
            image: 'img/social-card.png',
            colorMode: {
                respectPrefersColorScheme: true,
            },
            navbar: {
                title: 'Dirthara',
                logo: {
                    alt: 'Dirthara',
                    src: 'img/logo.png',
                },
                items: [
                    {
                        type: 'docSidebar',
                        sidebarId: 'docs',
                        position: 'left',
                        label: 'Documentation',
                    },
                    { to: '/blog', label: 'Release notes', position: 'left' },
                    { type: 'docsVersionDropdown', position: 'right' },
                    {
                        href: 'https://github.com/dirthara',
                        label: 'GitHub',
                        position: 'right',
                    },
                ],
            },
            footer: {
                style: 'dark',
                links: [
                    {
                        title: 'Packages',
                        items: Object.entries(sources.packages)
                            .sort(([, a], [, b]) => (a.position ?? 99) - (b.position ?? 99))
                            .map(([name, pkg]) => ({
                                label: pkg.label ?? name,
                                // Every package opens on `docs/intro.md`, which
                                // the package template ships from the first
                                // commit. The category path is not a link: it
                                // only resolves for a package that happens to
                                // carry a page named after itself.
                                to: `/${currentVersion.name}/${name}/intro`,
                            })),
                    },
                    {
                        title: 'More',
                        items: [
                            { label: 'Release notes', to: '/blog' },
                            { label: 'GitHub', href: 'https://github.com/dirthara' },
                        ],
                    },
                ],
                copyright: `Copyright © ${new Date().getFullYear()} Dirthara. Documentation released under the MIT License.`,
            },
            prism: {
                theme: prismThemes.github,
                darkTheme: prismThemes.dracula,
                // PHP is not in Prism's default bundle, and it is most of what
                // every code block on this site contains.
                additionalLanguages: ['php', 'bash', 'json', 'sql', 'ini', 'diff', 'yaml'],
            },
        }),
};

export default config;
