// One sidebar for the whole site, generated from what pull-docs.mjs laid down.
//
// Each package becomes a category through the `_category_.json` the pull script
// writes, and the pages inside it order themselves by the `sidebar_position` in
// their own front matter. Nothing here needs to change when a package is added
// or a page is renamed — that stays a fact about the package repository.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docs: [
        {
            type: 'autogenerated',
            dirName: '.',
        },
    ],
};

export default sidebars;
